BING_KEY_DEVEL=''
DB_USER_DEVEL='docker'
DB_PW_DEVEL='docker'
#LDAP_USER_DEVEL='cn=yourbinduser,dc=yoursubdomain,dc=yourdomain,dc=com'
#LDAP_PW_DEVEL='yourldappass'
GEOSERVER_USER_DEVEL='admin'
GEOSERVER_PW_DEVEL='geoserver'
